// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeU4jUut1CdmTKpF4ZD8TFUIUIQ_CWncQ',
    appId: '1:881754597543:web:779fba1c226c2c8b805382',
    messagingSenderId: '881754597543',
    projectId: 'drug-distribution-system',
    authDomain: 'drug-distribution-system.firebaseapp.com',
    storageBucket: 'drug-distribution-system.appspot.com',
    measurementId: 'G-6CKHFKLC12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN2tQ5czqO5LlGJN5AA724dF9w2QgbYzg',
    appId: '1:881754597543:android:6e58dd623c626476805382',
    messagingSenderId: '881754597543',
    projectId: 'drug-distribution-system',
    storageBucket: 'drug-distribution-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbBehTxC6R4EhHSWvRAWteP3gkpAv0uRM',
    appId: '1:881754597543:ios:ce23063459f7d775805382',
    messagingSenderId: '881754597543',
    projectId: 'drug-distribution-system',
    storageBucket: 'drug-distribution-system.appspot.com',
    androidClientId:
        '881754597543-dlflvlnf4d54cmmebo6rpaplsliap2po.apps.googleusercontent.com',
    iosClientId:
        '881754597543-r31iek5l53k4rhi1onikuhgfqbsp45t0.apps.googleusercontent.com',
    iosBundleId: 'com.phil.dbs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbBehTxC6R4EhHSWvRAWteP3gkpAv0uRM',
    appId: '1:881754597543:ios:ce23063459f7d775805382',
    messagingSenderId: '881754597543',
    projectId: 'drug-distribution-system',
    storageBucket: 'drug-distribution-system.appspot.com',
    androidClientId:
        '881754597543-dlflvlnf4d54cmmebo6rpaplsliap2po.apps.googleusercontent.com',
    iosClientId:
        '881754597543-r31iek5l53k4rhi1onikuhgfqbsp45t0.apps.googleusercontent.com',
    iosBundleId: 'com.phil.dbs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeU4jUut1CdmTKpF4ZD8TFUIUIQ_CWncQ',
    appId: '1:881754597543:web:3a4829ae61d1eae7805382',
    messagingSenderId: '881754597543',
    projectId: 'drug-distribution-system',
    authDomain: 'drug-distribution-system.firebaseapp.com',
    storageBucket: 'drug-distribution-system.appspot.com',
    measurementId: 'G-8D1EF364BQ',
  );
}
